/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const CreateOrderInput = IDL.Record({
  'serviceType' : IDL.Text,
  'clientName' : IDL.Text,
  'quoteId' : IDL.Opt(IDL.Nat),
  'description' : IDL.Text,
  'amount' : IDL.Float64,
});
export const OrderStatus = IDL.Variant({
  'Delivered' : IDL.Null,
  'Ready' : IDL.Null,
  'InProgress' : IDL.Null,
  'Pending' : IDL.Null,
});
export const Order = IDL.Record({
  'id' : IDL.Nat,
  'status' : OrderStatus,
  'serviceType' : IDL.Text,
  'clientName' : IDL.Text,
  'createdAt' : IDL.Int,
  'quoteId' : IDL.Opt(IDL.Nat),
  'description' : IDL.Text,
  'updatedAt' : IDL.Int,
  'amount' : IDL.Float64,
});
export const CreatePortfolioItemInput = IDL.Record({
  'title' : IDL.Text,
  'serviceCategory' : IDL.Text,
  'displayOrder' : IDL.Nat,
  'imageUrl' : IDL.Text,
  'isVisible' : IDL.Bool,
});
export const PortfolioItem = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'serviceCategory' : IDL.Text,
  'displayOrder' : IDL.Nat,
  'imageUrl' : IDL.Text,
  'isVisible' : IDL.Bool,
});
export const CreateQuoteInput = IDL.Record({
  'serviceType' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'phone' : IDL.Text,
  'budgetRange' : IDL.Text,
  'projectDetails' : IDL.Text,
  'timeline' : IDL.Text,
});
export const QuoteStatus = IDL.Variant({
  'New' : IDL.Null,
  'Won' : IDL.Null,
  'Lost' : IDL.Null,
  'Contacted' : IDL.Null,
});
export const Quote = IDL.Record({
  'id' : IDL.Nat,
  'status' : QuoteStatus,
  'serviceType' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'email' : IDL.Text,
  'phone' : IDL.Text,
  'budgetRange' : IDL.Text,
  'projectDetails' : IDL.Text,
  'timeline' : IDL.Text,
});
export const CreateServiceInput = IDL.Record({
  'displayOrder' : IDL.Nat,
  'icon' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'isActive' : IDL.Bool,
  'imageUrl' : IDL.Opt(IDL.Text),
});
export const Service = IDL.Record({
  'id' : IDL.Nat,
  'displayOrder' : IDL.Nat,
  'icon' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'isActive' : IDL.Bool,
  'imageUrl' : IDL.Opt(IDL.Text),
});
export const CreateTestimonialInput = IDL.Record({
  'clientName' : IDL.Text,
  'displayOrder' : IDL.Nat,
  'businessType' : IDL.Text,
  'quote' : IDL.Text,
  'isVisible' : IDL.Bool,
  'rating' : IDL.Nat,
});
export const Testimonial = IDL.Record({
  'id' : IDL.Nat,
  'clientName' : IDL.Text,
  'displayOrder' : IDL.Nat,
  'businessType' : IDL.Text,
  'quote' : IDL.Text,
  'isVisible' : IDL.Bool,
  'rating' : IDL.Nat,
});
export const ContentBlock = IDL.Record({
  'key' : IDL.Text,
  'value' : IDL.Text,
  'updatedAt' : IDL.Int,
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControl' : IDL.Func([], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createOrder' : IDL.Func([CreateOrderInput], [Order], []),
  'createPortfolioItem' : IDL.Func(
      [CreatePortfolioItemInput],
      [PortfolioItem],
      [],
    ),
  'createQuote' : IDL.Func([CreateQuoteInput], [Quote], []),
  'createService' : IDL.Func([CreateServiceInput], [Service], []),
  'createTestimonial' : IDL.Func([CreateTestimonialInput], [Testimonial], []),
  'deletePortfolioItem' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteService' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteTestimonial' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], []),
  'getAllQuotes' : IDL.Func([], [IDL.Vec(Quote)], []),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getContentBlock' : IDL.Func([IDL.Text], [IDL.Opt(ContentBlock)], ['query']),
  'getContentBlocks' : IDL.Func([], [IDL.Vec(ContentBlock)], ['query']),
  'getOrder' : IDL.Func([IDL.Nat], [IDL.Opt(Order)], []),
  'getPortfolioItems' : IDL.Func([], [IDL.Vec(PortfolioItem)], ['query']),
  'getQuote' : IDL.Func([IDL.Nat], [IDL.Opt(Quote)], []),
  'getServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
  'getTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'setContentBlock' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'updateOrderStatus' : IDL.Func([IDL.Nat, OrderStatus], [IDL.Bool], []),
  'updatePortfolioItem' : IDL.Func(
      [IDL.Nat, CreatePortfolioItemInput],
      [IDL.Bool],
      [],
    ),
  'updateQuoteStatus' : IDL.Func([IDL.Nat, QuoteStatus], [IDL.Bool], []),
  'updateService' : IDL.Func([IDL.Nat, CreateServiceInput], [IDL.Bool], []),
  'updateTestimonial' : IDL.Func(
      [IDL.Nat, CreateTestimonialInput],
      [IDL.Bool],
      [],
    ),
  'verifyAdminCredentials' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Bool],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const CreateOrderInput = IDL.Record({
    'serviceType' : IDL.Text,
    'clientName' : IDL.Text,
    'quoteId' : IDL.Opt(IDL.Nat),
    'description' : IDL.Text,
    'amount' : IDL.Float64,
  });
  const OrderStatus = IDL.Variant({
    'Delivered' : IDL.Null,
    'Ready' : IDL.Null,
    'InProgress' : IDL.Null,
    'Pending' : IDL.Null,
  });
  const Order = IDL.Record({
    'id' : IDL.Nat,
    'status' : OrderStatus,
    'serviceType' : IDL.Text,
    'clientName' : IDL.Text,
    'createdAt' : IDL.Int,
    'quoteId' : IDL.Opt(IDL.Nat),
    'description' : IDL.Text,
    'updatedAt' : IDL.Int,
    'amount' : IDL.Float64,
  });
  const CreatePortfolioItemInput = IDL.Record({
    'title' : IDL.Text,
    'serviceCategory' : IDL.Text,
    'displayOrder' : IDL.Nat,
    'imageUrl' : IDL.Text,
    'isVisible' : IDL.Bool,
  });
  const PortfolioItem = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'serviceCategory' : IDL.Text,
    'displayOrder' : IDL.Nat,
    'imageUrl' : IDL.Text,
    'isVisible' : IDL.Bool,
  });
  const CreateQuoteInput = IDL.Record({
    'serviceType' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'phone' : IDL.Text,
    'budgetRange' : IDL.Text,
    'projectDetails' : IDL.Text,
    'timeline' : IDL.Text,
  });
  const QuoteStatus = IDL.Variant({
    'New' : IDL.Null,
    'Won' : IDL.Null,
    'Lost' : IDL.Null,
    'Contacted' : IDL.Null,
  });
  const Quote = IDL.Record({
    'id' : IDL.Nat,
    'status' : QuoteStatus,
    'serviceType' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'email' : IDL.Text,
    'phone' : IDL.Text,
    'budgetRange' : IDL.Text,
    'projectDetails' : IDL.Text,
    'timeline' : IDL.Text,
  });
  const CreateServiceInput = IDL.Record({
    'displayOrder' : IDL.Nat,
    'icon' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'isActive' : IDL.Bool,
    'imageUrl' : IDL.Opt(IDL.Text),
  });
  const Service = IDL.Record({
    'id' : IDL.Nat,
    'displayOrder' : IDL.Nat,
    'icon' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'isActive' : IDL.Bool,
    'imageUrl' : IDL.Opt(IDL.Text),
  });
  const CreateTestimonialInput = IDL.Record({
    'clientName' : IDL.Text,
    'displayOrder' : IDL.Nat,
    'businessType' : IDL.Text,
    'quote' : IDL.Text,
    'isVisible' : IDL.Bool,
    'rating' : IDL.Nat,
  });
  const Testimonial = IDL.Record({
    'id' : IDL.Nat,
    'clientName' : IDL.Text,
    'displayOrder' : IDL.Nat,
    'businessType' : IDL.Text,
    'quote' : IDL.Text,
    'isVisible' : IDL.Bool,
    'rating' : IDL.Nat,
  });
  const ContentBlock = IDL.Record({
    'key' : IDL.Text,
    'value' : IDL.Text,
    'updatedAt' : IDL.Int,
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControl' : IDL.Func([], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createOrder' : IDL.Func([CreateOrderInput], [Order], []),
    'createPortfolioItem' : IDL.Func(
        [CreatePortfolioItemInput],
        [PortfolioItem],
        [],
      ),
    'createQuote' : IDL.Func([CreateQuoteInput], [Quote], []),
    'createService' : IDL.Func([CreateServiceInput], [Service], []),
    'createTestimonial' : IDL.Func([CreateTestimonialInput], [Testimonial], []),
    'deletePortfolioItem' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteService' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteTestimonial' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], []),
    'getAllQuotes' : IDL.Func([], [IDL.Vec(Quote)], []),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getContentBlock' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(ContentBlock)],
        ['query'],
      ),
    'getContentBlocks' : IDL.Func([], [IDL.Vec(ContentBlock)], ['query']),
    'getOrder' : IDL.Func([IDL.Nat], [IDL.Opt(Order)], []),
    'getPortfolioItems' : IDL.Func([], [IDL.Vec(PortfolioItem)], ['query']),
    'getQuote' : IDL.Func([IDL.Nat], [IDL.Opt(Quote)], []),
    'getServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
    'getTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'setContentBlock' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'updateOrderStatus' : IDL.Func([IDL.Nat, OrderStatus], [IDL.Bool], []),
    'updatePortfolioItem' : IDL.Func(
        [IDL.Nat, CreatePortfolioItemInput],
        [IDL.Bool],
        [],
      ),
    'updateQuoteStatus' : IDL.Func([IDL.Nat, QuoteStatus], [IDL.Bool], []),
    'updateService' : IDL.Func([IDL.Nat, CreateServiceInput], [IDL.Bool], []),
    'updateTestimonial' : IDL.Func(
        [IDL.Nat, CreateTestimonialInput],
        [IDL.Bool],
        [],
      ),
    'verifyAdminCredentials' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Bool],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };