/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ContentBlock {
  'key' : string,
  'value' : string,
  'updatedAt' : bigint,
}
export interface CreateOrderInput {
  'serviceType' : string,
  'clientName' : string,
  'quoteId' : [] | [bigint],
  'description' : string,
  'amount' : number,
}
export interface CreatePortfolioItemInput {
  'title' : string,
  'serviceCategory' : string,
  'displayOrder' : bigint,
  'imageUrl' : string,
  'isVisible' : boolean,
}
export interface CreateQuoteInput {
  'serviceType' : string,
  'name' : string,
  'email' : string,
  'phone' : string,
  'budgetRange' : string,
  'projectDetails' : string,
  'timeline' : string,
}
export interface CreateServiceInput {
  'displayOrder' : bigint,
  'icon' : string,
  'name' : string,
  'description' : string,
  'isActive' : boolean,
  'imageUrl' : [] | [string],
}
export interface CreateTestimonialInput {
  'clientName' : string,
  'displayOrder' : bigint,
  'businessType' : string,
  'quote' : string,
  'isVisible' : boolean,
  'rating' : bigint,
}
export interface Order {
  'id' : bigint,
  'status' : OrderStatus,
  'serviceType' : string,
  'clientName' : string,
  'createdAt' : bigint,
  'quoteId' : [] | [bigint],
  'description' : string,
  'updatedAt' : bigint,
  'amount' : number,
}
export type OrderStatus = { 'Delivered' : null } |
  { 'Ready' : null } |
  { 'InProgress' : null } |
  { 'Pending' : null };
export interface PortfolioItem {
  'id' : bigint,
  'title' : string,
  'serviceCategory' : string,
  'displayOrder' : bigint,
  'imageUrl' : string,
  'isVisible' : boolean,
}
export interface Quote {
  'id' : bigint,
  'status' : QuoteStatus,
  'serviceType' : string,
  'name' : string,
  'createdAt' : bigint,
  'email' : string,
  'phone' : string,
  'budgetRange' : string,
  'projectDetails' : string,
  'timeline' : string,
}
export type QuoteStatus = { 'New' : null } |
  { 'Won' : null } |
  { 'Lost' : null } |
  { 'Contacted' : null };
export interface Service {
  'id' : bigint,
  'displayOrder' : bigint,
  'icon' : string,
  'name' : string,
  'description' : string,
  'isActive' : boolean,
  'imageUrl' : [] | [string],
}
export interface Testimonial {
  'id' : bigint,
  'clientName' : string,
  'displayOrder' : bigint,
  'businessType' : string,
  'quote' : string,
  'isVisible' : boolean,
  'rating' : bigint,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createOrder' : ActorMethod<[CreateOrderInput], Order>,
  'createPortfolioItem' : ActorMethod<
    [CreatePortfolioItemInput],
    PortfolioItem
  >,
  'createQuote' : ActorMethod<[CreateQuoteInput], Quote>,
  'createService' : ActorMethod<[CreateServiceInput], Service>,
  'createTestimonial' : ActorMethod<[CreateTestimonialInput], Testimonial>,
  'deletePortfolioItem' : ActorMethod<[bigint], boolean>,
  'deleteService' : ActorMethod<[bigint], boolean>,
  'deleteTestimonial' : ActorMethod<[bigint], boolean>,
  'getAllOrders' : ActorMethod<[], Array<Order>>,
  'getAllQuotes' : ActorMethod<[], Array<Quote>>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getContentBlock' : ActorMethod<[string], [] | [ContentBlock]>,
  'getContentBlocks' : ActorMethod<[], Array<ContentBlock>>,
  'getOrder' : ActorMethod<[bigint], [] | [Order]>,
  'getPortfolioItems' : ActorMethod<[], Array<PortfolioItem>>,
  'getQuote' : ActorMethod<[bigint], [] | [Quote]>,
  'getServices' : ActorMethod<[], Array<Service>>,
  'getTestimonials' : ActorMethod<[], Array<Testimonial>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'setContentBlock' : ActorMethod<[string, string], undefined>,
  'updateOrderStatus' : ActorMethod<[bigint, OrderStatus], boolean>,
  'updatePortfolioItem' : ActorMethod<
    [bigint, CreatePortfolioItemInput],
    boolean
  >,
  'updateQuoteStatus' : ActorMethod<[bigint, QuoteStatus], boolean>,
  'updateService' : ActorMethod<[bigint, CreateServiceInput], boolean>,
  'updateTestimonial' : ActorMethod<[bigint, CreateTestimonialInput], boolean>,
  'verifyAdminCredentials' : ActorMethod<[string, string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];